### ISSUE TITLE
Activity - Temperature

### ISSUE THREAD

**Issue by IanMSpencer** [SweetzpotAS/StravaZpot-Android#2] opened 2016-11-26 19:11 UTC
When downloading activities generated via a Garmin, i.e. fully populated, the Temperature field of Activity causes an error in JSON - OBJECT expected, number received.

I tried fully populating the Temperature class which seems to be a stub using Distance as a model, but the error still occurs.

Then spotted the type adapters - Temperature missing.

Fixes:

Temperature.java

public class Temperature {
    private float celsiusDegrees;
    public static Temperature celsiusDegrees(float celsiusDegrees) {
        return new Temperature(celsiusDegrees);
    }
    public Temperature(float celsiusDegrees) {
        this.celsiusDegrees = celsiusDegrees;
    }

    public float getCelsiusDegrees() {
        return celsiusDegrees;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Temperature temperature = (Temperature) o;

        return Float.compare(temperature.celsiusDegrees, celsiusDegrees) == 0;

    }

    @Override
    public int hashCode() {
        return (celsiusDegrees != +0.0f ? Float.floatToIntBits(celsiusDegrees) : 0);
    }

    @Override
    public String toString() {
        return String.valueOf(celsiusDegrees);
    }
}

TemperatureTypeAdapter

public class TemperatureTypeAdapter extends TypeAdapter<Temperature> {

    @Override
    public void write(JsonWriter out, Temperature value) throws IOException {
        out.value(value.getCelsiusDegrees());
    }

    @Override
    public Temperature read(JsonReader in) throws IOException {
        if(!in.peek().equals(JsonToken.NULL)) {
            return new Temperature((float) (in.nextDouble()));
        } else {
            return null;
        }
    }
}

and register the typeadapter in config.java

**Comment by truizlop** [comment] 2016-11-28 10:27
Thanks for your suggestion Ian. Since it seems you already got the fix for this issue, could you submit a pull request? If not, could you provide the JSON that is causing the issue, so that we can reproduce it and fix it ourselves? Thanks!

**Comment by IanMSpencer** [comment] 2016-11-28 11:01
Hi

Haven't yet worked out how to properly use GitHub, had to use a workaround to rebuild the code for my app under Android Studio 2.2 as I don't really understand the gradle system yet.

The problem will only occur if the data includes the average temperature of the activity. To reproduce:
1) Connect to an account where activities have been created using a device that records temperature (e.g. Garmin 800 series) and download an appropriate ride.
2)I think if you add average_temp to the data created in your activity test it will fail when you round trip the data.

The code is simply incomplete, so not a big deal to sort out once you look!

Not being unhelpful - just don't know what I'm doing!

**Comment by truizlop** [comment] 2016-11-28 11:14
Don't worry, I'll try to provide a fix soon. You have provided valuable feedback to discover the issue ;)

**Comment by truizlop** [comment] 2016-11-30 09:34
Hi Ian, I have just fixed the issue and published version 1.0.1 of our library. Please, update your Gradle build file to check out the new version where this issue is solved.

**Closed by truizlop** 2016-11-30 09:34 UTC
